[book]
tite = "Notes de cours sur l'intégration de l'électronique aux espaces immersifs"
authors = ["Thomas O Fredericks", "Guillaume Arseneault"]
language = "fr"
multilingual = false
src = "rel-electro-immersif-src"

[build]
build-dir = "docs"