[book]
tite = "Électronique pour espaces immersifs (REL)"
authors = ["Thomas O Fredericks", "Guillaume Arseneault"]
language = "fr"
multilingual = false
src = "rel-electro-immersif-src"

[build]
build-dir = "docs"